//VEHICLES

export const GET_VEHICLES = "GET_VEHICLES";
export const UPDATE_VEHICLE = "UPDATE_VEHICLE";
export const ADD_VEHICLE = "ADD_VEHICLE";
export const DELETE_VEHICLE = "DELETE_VEHICLE";

// RESERVATIONS

export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const UPDATE_RESERVATION = "UPDATE_RESERVATION";

// REPORTS

export const GET_REPORTS = "GET_REPORTS";
export const UPDATE_REPORT = "UPDATE_REPORT";

// LOGIN

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const INITIATE_LOGIN = "INITIATE_LOGIN";
export const GET_USER = "GET_USER";

// AGENCIES

export const GET_AGENCIES = "GET_AGENCIES";
export const UPDATE_AGENCY = "UPDATE_AGENCY";
export const ADD_AGENCY = "ADD_AGENCY";
export const DELETE_AGENCY = "DELETE_AGENCY";

// VEHICLE SIZES

export const GET_SIZES = "GET_SIZES";
export const UPDATE_SIZE = "UPDATE_SIZE";
export const ADD_SIZE = "ADD_SIZE";
export const DELETE_SIZE = "DELETE_SIZE";

// FUEL TYPES

export const GET_FUEL_TYPES = "GET_FUEL_TYPES";
export const UPDATE_FUEL_TYPE = "UPDATE_FUEL_TYPE";
export const ADD_FUEL_TYPE = "ADD_FUEL_TYPE";
export const DELETE_FUEL_TYPE = "DELETE_FUEL_TYPE";

// ADDITIONS

export const GET_ADDITIONS = "GET_ADDITIONS";
export const UPDATE_ADDITION = "UPDATE_ADDITION";
export const ADD_ADDITION = "ADD_ADDITION";
export const DELETE_ADDITION = "DELETE_ADDITION";

// CURRENCIES

export const GET_CURRENCIES = "GET_CURRENCIES";
export const UPDATE_CURRENCY = "UPDATE_CURRENCY";
export const ADD_CURRENCY = "ADD_CURRENCY";
export const DELETE_CURRENCY = "DELETE_CURRENCY";
